name: CI/CD Pipeline
on:
  push:
    tags:
      - "*"
jobs:
  run-script:
    name: Create yandex issue
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Creating ticket and pushing to Yandex.Tracker
      run: |
        chmod +x ./scripts/create_ticket_script.sh
        ./scripts/create_ticket_script.sh
      env:
        OAuth: ${secrets.OAUTH}
        OrgID: ${secrets.ORGID}

    - uses: actions/setup-node@v2
      with:
        node-version: '14'
    - name: npm install
      run: npm install --silent
    - name: Run tests
      run: npm test

  #run-tests:

  #docker-build-image:
