name: CI/CD Pipeline
on:
  push:
    tags:
      - "*"
jobs:
  install_and_test:
    name: Install and test
    runs-on: ubuntu-latest
    steps:
    - uses: action/setup-node@v1
    - name: Setup node
      run: npm install --silent
    - name: Run tests
      run: jest

  create_ticket:
    name: Creating ticket and pushing to Yandex.Tracker
    runs-on: ubuntu-latest
    steps:
      - name: Run bash script
        run: |
          chmod +x create_ticket_script.sh
          create_ticket_script.sh
        env:
          OAuth: ${secrets.OAuth}
          OrgID: ${secrets.OrgID}
  #run-tests:

  #docker-build-image:
