name: CI/CD Pipeline
on: 
  release:
    branches:
      - master
    tags:
      - v.*.*.*
    if: startsWith(github.ref, 'refs/tags/v')
jobs:
  install_and_serve:
    name: Install and serve
    runs-on: ubuntu-latest
    steps:
    - uses: action/setup-node@v1
      with:
        node-version: '14'
    - run: npm install | npm test | npm start

#jobs:
 # install_and_serve:
  #  name: Install and serve
   # runs-on: ubuntu-latest
    #steps:
    #- uses: actions/checkout@v2
    #- uses: actions/setup-node@v2
    #  with:
    #    node-version: '14'
    #- run: npm install -g bats
    #- run: npm test
    #- run: bats -v
    #- run: npm start
